// models/booking_model.dart (or booking_request.dart if you prefer)
import 'package:intl/intl.dart'; // For date parsing and formatting, if needed for display

class Booking {
  // Fields based on your OpenSpaceBooking Django model
  final String id; // Assuming your API sends an 'id' for each booking when fetched
  final int spaceId; // From space ForeignKey (ID)
  final String? userId; // From user ForeignKey (ID), nullable
  final String username;
  final String contact;
  final DateTime startDate; // Parsed from 'startdate' string
  final DateTime? endDate; // Parsed from 'enddate' string, nullable
  final String purpose;
  final String district;
  final String? fileUrl; // URL of the uploaded file, nullable
  final DateTime createdAt; // Parsed from 'created_at' string
  final String status; // e.g., 'pending', 'accepted', 'rejected'

  Booking({
    required this.id,
    required this.spaceId,
    this.userId,
    required this.username,
    required this.contact,
    required this.startDate,
    this.endDate,
    required this.purpose,
    required this.district,
    this.fileUrl,
    required this.createdAt,
    required this.status,
  });

  /// Converts this Booking object into a JSON map.
  /// This is used when SENDING data TO the backend for CREATING a booking.
  /// It should align with what the create booking endpoint expects.
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {
      'space': spaceId, // Ensure your backend expects 'space' as the key for space_id
      'username': username,
      'contact': contact,
      // For toJson, we might send dates as strings in "YYYY-MM-DD" format
      // if the createBooking endpoint expects that (which is common).
      'startdate': DateFormat('yyyy-MM-dd').format(startDate),
      'purpose': purpose,
      'district': district,
      // 'status' is usually set by the backend on creation.
      // 'user' (user ID) is also usually derived by the backend from the auth token.
    };
    if (endDate != null) {
      data['enddate'] = DateFormat('yyyy-MM-dd').format(endDate!);
    }
    // 'file' is handled separately by MultipartRequest if present, not in this JSON.
    // 'id' and 'created_at' are usually generated by the backend.
    return data;
  }
  factory Booking.fromJson(Map<String, dynamic> json) {
    // Helper to safely parse dates from string
    DateTime? _parseDate(String? dateStr) {
      if (dateStr == null || dateStr.isEmpty) return null;
      try {
        return DateTime.parse(dateStr);
      } catch (e) {
        print("Error parsing date string '$dateStr': $e");
        return null;
      }
    }
    final int spaceIdFromJson = (json['space'] is int)
        ? json['space']
        : (json['space'] is String ? int.tryParse(json['space'] ?? '') ?? 0 : 0);

    final String? userIdFromJson = json['user']?.toString();

    DateTime parsedStartDate = _parseDate(json['startdate']) ?? DateTime.now(); // Fallback
    DateTime? parsedEndDate = _parseDate(json['enddate']); // Nullable
    DateTime parsedCreatedAt = _parseDate(json['created_at']) ?? DateTime.now(); // Fallback

    if (json['id'] == null) {
      print("Error: Booking JSON missing 'id'. This is critical for fetched bookings.");
    }
    if (json['startdate'] == null) {
      print("Warning: Booking JSON (id: ${json['id']}) missing 'startdate'. Using current date as fallback.");
    }

    return Booking(
      id: json['id']?.toString() ?? 'temp_id_${DateTime.now().millisecondsSinceEpoch}',
      spaceId: spaceIdFromJson,
      userId: userIdFromJson,
      username: json['username'] ?? 'N/A',
      contact: json['contact'] ?? 'N/A',
      startDate: parsedStartDate,
      endDate: parsedEndDate,
      purpose: json['purpose'] ?? 'No purpose specified',
      district: json['district'] ?? 'Kinondoni',
      fileUrl: json['file'],
      createdAt: parsedCreatedAt,
      status: json['status']?.toLowerCase() ?? 'pending',
    );
  }


  int get calculatedDurationInDays {
    if (endDate == null) {
      return 1;
    }
    if (endDate!.isBefore(startDate)) {
      return 1;
    }
    return endDate!.difference(startDate).inDays + 1;
  }
}